var quiz_list = [
    {question: "가장 좋아하는 계절은?", choices: ["봄", "여름", "가을", "겨울"]},
    {question: "가장 좋아하는 가수는?", choices: ["Bruno Mars", "Justin Bieber", "Ariana Grande", "Charlie Puth"]},
    {question: "가장 좋아하는 색상은?", choices: ["빨강", "파랑", "초록", "노랑"]},
    {question: "가장 좋아하는 동물은?", choices: ["고양이", "강아지", "토끼", "새"]},
    {question: "가장 좋아하는 음식은?", choices: ["피자", "파스타", "햄버거", "샐러드"]},
    {question: "가장 좋아하는 스포츠는?", choices: ["축구", "농구", "야구", "테니스"]},
    {question: "가장 좋아하는 영화 장르는?", choices: ["코미디", "로맨스", "스릴러", "공포"]},
    {question: "가장 좋아하는 음료는?", choices: ["커피", "차", "소다", "주스"]},
    {question: "가장 좋아하는 학과는?", choices: ["문과", "이과", "예술과", "체육과"]},
    {question: "가장 좋아하는 가구는?", choices: ["침대", "소파", "책상", "식탁"]},
    {question: "가장 좋아하는 꽃은?", choices: ["장미", "튤립", "해바라기", "라일락"]},
    {question: "가장 좋아하는 계절은?", choices: ["봄", "여름", "가을", "겨울"]},
    {question: "가장 좋아하는 음악 장르는?", choices: ["팝", "클래식", "재즈", "락"]},
    {question: "가장 좋아하는 여행지는?", choices: ["해변", "산", "도시", "시골"]},
    {question: "가장 좋아하는 자동차 브랜드는?", choices: ["BMW", "Audi", "Mercedes Benz", "Tesla"]},
    {question: "가장 좋아하는 가전 제품은?", choices: ["TV", "냉장고", "에어컨", "세탁기"]},
    {question: "가장 좋아하는 애니메이션 캐릭터는?", choices: ["미키마우스", "스폰지밥", "심슨가족", "포켓몬스터"]},
    {question: "가장 좋아하는 사계절 음식은?", choices: ["떡국", "삼겹살", "초밥", "피자"]},
    {question: "가장 좋아하는 과일은?", choices: ["사과", "바나나", "딸기", "오렌지"]},
    {question: "가장 좋아하는 책 장르는?", choices: ["소설", "시", "에세이", "자기계발"]},
    {question: "가장 좋아하는 학교 과목은?", choices: ["수학", "과학", "영어", "역사"]},
    {question: "가장 좋아하는 TV 프로그램 장르는?", choices: ["드라마", "예능", "뉴스", "다큐멘터리"]},
    {question: "가장 좋아하는 게임 장르는?", choices: ["RPG", "FPS", "스포츠", "전략"]},
    {question: "가장 좋아하는 사탕은?", choices: ["젤리", "초콜릿", "사탕수수", "누가바"]},
    {question: "가장 좋아하는 유튜브 채널 장르는?", choices: ["먹방", "여행", "교육", "뷰티"]},
    {question: "가장 좋아하는 휴가 스타일은?", choices: ["모험", "휴식", "사진 촬영", "음식 탐색"]},
    {question: "가장 좋아하는 스마트폰 브랜드는?", choices: ["Apple", "Samsung", "Google", "Huawei"]},
    {question: "가장 좋아하는 집안일은?", choices: ["청소", "요리", "세탁", "정리정돈"]},
];
