const fortune_list = [
    "1. 인내는 쓰지만 그 열매는 달다. - Jean-Jacques Rousseau",
    "2. 고난은 용기와 희망을 키운다. - Lope de Vega",
    "3. 모든 성취의 시작점은 갈망이다. - Napoleon Hill",
    "4. 어제의 나와 경쟁하라. - William Faulkner",
    "5. 시간은 최고의 투자가 될 수 있다. - Benjamin Franklin",
    "6. 자신을 믿어라. - Helen Keller",
    "7. 모든 아름다움은 간단함에서 비롯된다. - Leonardo Da Vinci",
    "8. 성공이란 단순히 더 많이 시도하는 것에서 온다. - Thomas Edison",
    "9. 고난 없이는 아무런 진보도 없다. - Frederick Douglass",
    "10. 참을성과 시간이 결국 가장 강력하다. - Miguel de Cervantes",
    "11. 목표를 세우고, 꿈을 꾸고, 앞으로 나아가라. - Confucius",
    "12. 일단 시작하면 절반은 이미 성공한 것이다. - Zen Saying",
    "13. 용기 있는 자가 이긴다. - Virgil",
    "14. 도전이 기회로 변한다. - Richard Branson",
    "15. 자신감은 당신의 힘이다. - Zig Ziglar",
    "16. 포기하지 마라, 참을성이 성공의 열쇠다. - Bill Gates",
    "17. 오늘은 어제보다 나은 하루가 되도록 노력하라. - Mahatma Gandhi",
    "18. 도전은 삶을 흥미롭게 만든다. - Eleanor Roosevelt",
    "19. 실패는 성공으로 가는 임시적인 정체일 뿐이다. - Henry Ford",
    "20. 진정한 용기는 두려움을 극복하는 것이다. - Nelson Mandela",
    "21. 큰 기회는 종종 어려움 속에서 발견된다. - Napoleon Hill",
    "22. 오늘 할 수 있는 일을 내일로 미루지 마라. - Benjamin Franklin",
    "23. 인내와 노력 없이는 아무것도 얻을 수 없다. - Beethoven",
    "24. 가장 강한 인간은 가장 독립적인 자이다. - Sigmund Freud",
    "25. 성공의 비결은 목표를 가지고 있고 그 목표에 끊임없이 투자하는 것이다. - Albert Einstein",
    "26. 절대로 기대하지 않은 곳에서 가장 큰 기회를 찾을 수 있다. - Mark Zuckerberg",
    "27. 목표가 없다면 도착할 수 없다. - Zig Ziglar",
    "28. 용기는 계속 전진하는 것이다. - Winston Churchill",
    "29. 실패는 성공에 대한 첫걸음이다. - Walt Disney",
    "30. 결정은 행동을 촉진시킨다. - Tony Robbins",
    "31. 모든 성취는 결단에서 시작된다. - B.C. Forbes",
    "32. 적극성은 성공의 열쇠다. - Dale Carnegie",
    "33. 자신을 믿고 무엇이든 해라. - Walt Disney",
    "34. 불가능은 실제로는 존재하지 않는다. - Nelson Mandela",
    "35. 인생은 우리가 만드는 것이다. - Mahatma Gandhi",
    "36. 모든 굴곡에는 길이 있다. - John F. Kennedy",
    "37. 아무것도 도전하지 않으면 아무것도 이길 수 없다. - Michael Jordan",
    "38. 삶에 대한 열정이 성공을 보장한다. - Bruce Lee",
    "39. 도전은 생명의 본질이다. - Richard Branson",
    "40. 진정한 성공은 행복에서 비롯된다. - Dalai Lama",
    "41. 꿈은 현실이 될 수 있다. - Walt Disney",
    "42. 아무런 위험이 없는 곳에서는 아무것도 이룰 수 없다. - Andre Gide",
    "43. 두려움 없이 무엇이든지 도전하라. - Richard Branson",
    "44. 변화는 피할 수 없다. - Heraclitus",
    "45. 결코 포기하지 마라. - Winston Churchill",
    "46. 성공은 준비가 만나기를 기다리는 기회다. - Seneca",
    "47. 성공은 항상 노력의 결과다. - Dalai Lama",
    "48. 성공은 준비된 마음이 기회를 만날 때 생긴다. - Bobby Unser",
    "49. 성공은 행동에서 시작된다. - Zig Ziglar",
    "50. 실패는 학습의 시작이다. - Henry Ford",
    "51. 당신의 생각이 당신의 삶을 결정한다. - Confucius",
    "52. 목표를 위해 꾸준히 노력하라. - Babe Ruth",
    "53. 무엇이든지 시작하는 것이 가장 중요하다. - Mark Twain",
    "54. 변화를 두려워하지 마라. - Aristotle",
    "55. 나에게 용기를 준 것은 나의 두려움이었다. - Erica Jong",
    "56. 성공은 노력에서 생겨난다. - Vince Lombardi",
    "57. 실패는 성공을 위한 발판이다. - Robert Kiyosaki",
    "58. 절대로 포기하지 마라. - Harriet Stowe",
    "59. 적절한 시기에 행동하라. - Johann Wolfgang von Goethe",
    "60. 아무것도 불가능하지 않다. - Audrey Hepburn",
    "61. 용기는 위험에 대한 두려움을 이겨내는 것이다. - Ambrose Redmoon",
    "62. 우리의 목표는 당신의 꿈을 위해 노력하는 것이다. - Ralph Waldo Emerson",
    "63. 아무것도 도전하지 않으면 아무것도 이기지 못한다. - Maya Angelou",
    "64. 모든 건 충분히 가능하다. - Marcus Aurelius",
    "65. 모든 업적은 믿음에서 시작된다. - David Schwartz",
    "66. 꿈은 계획에 불과하다. - Peter Drucker",
    "67. 두려움은 용기 없는 사람들이 만든 것이다. - Dale Carnegie",
    "68. 성공은 당신이 원하는 것을 얻는 것이다. - Zig Ziglar",
    "69. 우리는 우리 자신의 행운을 만든다. - Earl Nightingale",
    "70. 당신은 당신이 결정한 것이다. - Robert Schuller",
    "71. 당신이 생각하는 것이 당신이 되는 것이다. - Buddha",
    "72. 용기는 두려움을 극복하는 것이다. - Eleanor Roosevelt",
    "73. 성공은 공포를 뛰어넘는 것이다. - Eleanor Roosevelt",
    "74. 꿈을 꾸라. 그럼 꿈은 당신을 찾아올 것이다. - Les Brown",
    "75. 용기는 사람이 얻을 수 있는 가장 위대한 품질이다. - Winston Churchill",
    "76. 지혜로움은 기회를 잡아라. - Francis Bacon",
    "77. 행동은 모든 성공의 기초이다. - Pablo Picasso",
    "78. 도전은 기회를 발견하는 것이다. - Swami Sivananda",
    "79. 성공은 용기를 가진 사람들에게 찾아온다. - Anais Nin",
    "80. 행동은 모든 성공의 열쇠다. - Benjamin Disraeli",
    "81. 성공은 끊임없는 노력에서 온다. - Mahatma Gandhi",
    "82. 성공은 끊임없는 노력에서 온다. - Mahatma Gandhi",
    "83. 변화를 두려워하지 마라. 변화는 진보다. - Robert Kennedy",
    "84. 행동은 성공으로 이끈다. - Zig Ziglar",
    "85. 도전은 기회를 만든다. - George S. Patton",
    "86. 어려움 속에서 성공을 찾아라. - Robert Schuller",
    "87. 성공은 준비된 마음에서 생겨난다. - Louis Pasteur",
    "88. 성공은 끊임없는 노력에서 온다. - Napoleon Hill",
    "89. 행동은 성공의 기본이다. - Norman Vincent Peale",
    "90. 성공은 끊임없는 노력의 결과다. - John D. Rockefeller",
    "91. 행동으로 시간을 이용하라. - Johann Wolfgang von Goethe",
    "92. 두려움은 용기 없이는 없다. - Nelson Mandela",
    "93. 꿈을 이루려면 깨어 있어야 한다. - Paul Valery",
    "94. 노력은 결코 배신하지 않는다. - Beethoven",
    "95. 문제는 기회이다. - John F. Kennedy",
    "96. 모든 변화는 행동에서 시작된다. - Socrates",
    "97. 도전은 삶의 향신료다. - William Penn",
    "98. 조금씩 항상 앞으로 나아가라. - Martin Luther King Jr.",
    "99. 실패는 성공으로의 한 걸음이다. - Denis Waitley",
    "100. 모든 것은 생각에서 시작된다. - Lao Tzu"
];

module.exports = fortune_list;
